version: 2
jobs:
  build:
    docker:
      - image: kairosaero/dkr-circleci:production
    working_directory: /opt/kairos/build-home/repo
    steps:
      - checkout
      - store_artifacts:
          path: dist
          destination: build-artifacts
notify:
  webhooks:
    - url: https://bdoa77w3h0.execute-api.us-west-2.amazonaws.com/webhook/
workflows:
  version: 2
  kairos-workflow:
    jobs:
      - build:
          context: org-global
